USE [master]
GO
/****** Object:  Database [SWW1]    Script Date: 28.02.2022 09:44:23 ******/


/****** Object:  Database [SWW1]    Script Date: 27.02.2022 21:56:07 ******/
CREATE DATABASE [SWW1]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'SWW1', FILENAME = N'D:\SQL\MSSQL15.MSSQLSERVER\MSSQL\DATA\SWW1.mdf' , SIZE = 65535KB , MAXSIZE = UNLIMITED, FILEGROWTH = 50%), 
 FILEGROUP [P2] 
( NAME = N'SWW1_2', FILENAME = N'D:\SQL\MSSQL15.MSSQLSERVER\MSSQL\DATA\SWW1_2.mdf' , SIZE = 65535KB , MAXSIZE = UNLIMITED, FILEGROWTH = 50%), 
 FILEGROUP [P3] 
( NAME = N'SWW1_3', FILENAME = N'D:\SQL\MSSQL15.MSSQLSERVER\MSSQL\DATA\SWW1_3.mdf' , SIZE = 65535KB , MAXSIZE = UNLIMITED, FILEGROWTH = 50%), 
 FILEGROUP [P4] 
( NAME = N'SWW1_4', FILENAME = N'D:\SQL\MSSQL15.MSSQLSERVER\MSSQL\DATA\SWW1_4.mdf' , SIZE = 65535KB , MAXSIZE = UNLIMITED, FILEGROWTH = 50%)
 LOG ON 
( NAME = N'SWW1_log', FILENAME = N'D:\SQL\MSSQL15.MSSQLSERVER\MSSQL\DATA\SWW1_log.ldf' , SIZE = 65535KB , MAXSIZE = 2048GB , FILEGROWTH = 50% )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [SWW1] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [SWW1].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [SWW1] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [SWW1] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [SWW1] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [SWW1] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [SWW1] SET ARITHABORT OFF 
GO
ALTER DATABASE [SWW1] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [SWW1] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [SWW1] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [SWW1] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [SWW1] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [SWW1] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [SWW1] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [SWW1] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [SWW1] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [SWW1] SET  DISABLE_BROKER 
GO
ALTER DATABASE [SWW1] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [SWW1] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [SWW1] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [SWW1] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [SWW1] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [SWW1] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [SWW1] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [SWW1] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [SWW1] SET  MULTI_USER 
GO
ALTER DATABASE [SWW1] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [SWW1] SET DB_CHAINING OFF 
GO
ALTER DATABASE [SWW1] SET FILESTREAM( NON_TRANSACTED_ACCESS = READ_ONLY ) 
GO
ALTER DATABASE [SWW1] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [SWW1] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [SWW1] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [SWW1] SET QUERY_STORE = OFF
GO
USE [SWW1]
GO
ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = ON;
GO
USE [SWW1]
GO
/****** Object:  PartitionFunction [SessionTimePartFn]    Script Date: 27.02.2022 21:56:07 ******/
CREATE PARTITION FUNCTION [SessionTimePartFn](datetime) AS RANGE LEFT FOR VALUES (N'2021-12-27T00:00:00.000', N'2022-01-27T00:00:00.000', N'2022-02-27T00:00:00.000')
GO
/****** Object:  PartitionScheme [SessionTimePartSch]    Script Date: 27.02.2022 21:56:07 ******/
CREATE PARTITION SCHEME [SessionTimePartSch] AS PARTITION [SessionTimePartFn] TO ([P4], [P3], [P2], [PRIMARY])
GO
/****** Object:  Table [dbo].[GsmSessions]    Script Date: 27.02.2022 21:56:07 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[GsmSessions](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Time] [datetime] NOT NULL,
	[SessionID] [int] NOT NULL,
	[IMSI] [bigint] NOT NULL,
	[TMSI] [bigint] NOT NULL,
	[IMEI] [bigint] NOT NULL,
	[MSISDN] [bigint] NOT NULL,
	[MCC] [char](3) NOT NULL,
	[MNC] [char](5) NOT NULL,
	[LAC] [smallint] NOT NULL,
	[CellID] [int] NOT NULL
) ON [SessionTimePartSch]([Time])
GO
SET ANSI_PADDING ON
GO
/****** Object:  Index [BTSIdx]    Script Date: 27.02.2022 21:56:07 ******/
CREATE NONCLUSTERED INDEX [BTSIdx] ON [dbo].[GsmSessions]
(
	[MCC] ASC,
	[MNC] ASC,
	[LAC] ASC,
	[CellID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [SessionTimePartSch]([Time])
GO
/****** Object:  Index [IMSIIdx]    Script Date: 27.02.2022 21:56:07 ******/
CREATE NONCLUSTERED INDEX [IMSIIdx] ON [dbo].[GsmSessions]
(
	[IMSI] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [SessionTimePartSch]([Time])
GO
/****** Object:  Index [TimeIdx]    Script Date: 27.02.2022 21:56:07 ******/
CREATE NONCLUSTERED INDEX [TimeIdx] ON [dbo].[GsmSessions]
(
	[Time] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [SessionTimePartSch]([Time])
GO
USE [master]
GO
ALTER DATABASE [SWW1] SET  READ_WRITE 
GO
